apiVersion: v1
kind: Pod
metadata:
  name: o2-full-ci
  labels:
    mount-eos: "true"
spec:
  containers:
  - name: o2-full-ci
    image: oliverrietmann/o2-standalone:latest
    command: ["sh", "-c", "cp /mnt/secret/ssh-privatekey /root/.ssh/id_ecdsa && sleep infinity"]
    resources:
      requests:
        memory: "32Gi"
      limits:
        nvidia.com/gpu: 1
        memory: "64Gi"
    securityContext:
      runAsUser: 0 
      runAsGroup: 0
    volumeMounts:
    - name: dev-shm
      mountPath: /dev/shm
    - name: ssh-volume
      mountPath: /mnt/secret
    - name: gitconfig
      mountPath: /root/.gitconfig
      subPath: .gitconfig
    - name: o2-alice-volume
      mountPath: /root/alice
    - name: o2-standalone-volume
      mountPath: /root/standalone
  volumes:
  - name: dev-shm
    emptyDir:
      medium: Memory
      sizeLimit: 4Gi
  - name: ssh-volume
    secret:
      secretName: ssh-secret
      defaultMode: 0600
  - name: gitconfig
    configMap:
      name: gitconfig
  - name: o2-alice-volume
    persistentVolumeClaim:
      claimName: o2-alice-pvc
  - name: o2-standalone-volume
    persistentVolumeClaim:
      claimName: o2-standalone-pvc
  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-H100-NVL

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: o2-alice-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: shared

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: o2-standalone-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: shared



# dnf install hip-rocclr ocl-icd ocl-icd-devel hipcub rocthrust rocm-dev hipify-clang hiprand-devel hipblas-devel hipsparse-devel rocblas-devel rocrand-devel miopen-hip-devel hipfft-devel rccl-devel migraphx-devel rdma-core-devel hipblaslt-devel rocprim-devel
# dnf install time bc
# kubectl create secret generic orietman-alice-key --from-file=userkey.pem=/home/orietman/.globus/userkey.pem --from-file=usercert.pem=/home/orietman/.globus/usercert.pem
