apiVersion: v1
kind: Pod
metadata:
  name: soa-wrapper
  labels:
    mount-eos: "true"
    mount-cvmfs: "true"
spec:
  containers:
  - name: soa-wrapper
    image: registry.cern.ch/ngt-wp1.7/wp1.7-soa-wrapper:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    volumeMounts:
    - name: home-volume
      mountPath: /root
  volumes:
  - name: home-volume
    persistentVolumeClaim:
      claimName: soa-wrapper-pvc
  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-H100-NVL

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soa-wrapper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
